Token IDENTIFIER: next_random
Token COLON: :
Token KEYWORD_INTEGER: integer
Token SEMICOLON: ;
Token KEYWORD_DEF: def
Token IDENTIFIER: next
Token L_PARENTHESIS: (
Token R_PARENTHESIS: )
Token OP_MINUS: -
Token OP_GREATER: >
Token KEYWORD_INTEGER: integer
Token COLON: :
Token IDENTIFIER: next_random
Token OP_ASSIGN: =
Token L_PARENTHESIS: (
Token IDENTIFIER: next_random
Token OP_MUL: *
Token CONST_INT: 1103515245
Token OP_PLUS: +
Token CONST_INT: 12345
Token R_PARENTHESIS: )
Token OP_MOD: %
Token CONST_INT: 2147483648
Token SEMICOLON: ;
Token KEYWORD_IF: if
Token L_PARENTHESIS: (
Token IDENTIFIER: next_random
Token OP_LESS: <
Token CONST_INT: 0
Token R_PARENTHESIS: )
Token COLON: :
Token IDENTIFIER: next_random
Token OP_ASSIGN: =
Token OP_MINUS: -
Token IDENTIFIER: next_random
Token SEMICOLON: ;
Token KEYWORD_ENDIF: endif
Token SEMICOLON: ;
Token KEYWORD_RETURN: return
Token IDENTIFIER: next_random
Token SEMICOLON: ;
Token KEYWORD_ENDDEF: enddef
Token SEMICOLON: ;
Token KEYWORD_DEF: def
Token IDENTIFIER: swap
Token L_PARENTHESIS: (
Token IDENTIFIER: a
Token L_BRACKET: [
Token R_BRACKET: ]
Token COLON: :
Token KEYWORD_INTEGER: integer
Token COMMA: ,
Token IDENTIFIER: i
Token COLON: :
Token KEYWORD_INTEGER: integer
Token COMMA: ,
Token IDENTIFIER: j
Token COLON: :
Token KEYWORD_INTEGER: integer
Token R_PARENTHESIS: )
Token COLON: :
Token IDENTIFIER: temp
Token COLON: :
Token KEYWORD_INTEGER: integer
Token SEMICOLON: ;
Token IDENTIFIER: temp
Token OP_ASSIGN: =
Token IDENTIFIER: a
Token L_BRACKET: [
Token IDENTIFIER: i
Token R_BRACKET: ]
Token SEMICOLON: ;
Token IDENTIFIER: a
Token L_BRACKET: [
Token IDENTIFIER: i
Token R_BRACKET: ]
Token OP_ASSIGN: =
Token IDENTIFIER: a
Token L_BRACKET: [
Token IDENTIFIER: j
Token R_BRACKET: ]
Token SEMICOLON: ;
Token IDENTIFIER: a
Token L_BRACKET: [
Token IDENTIFIER: j
Token R_BRACKET: ]
Token OP_ASSIGN: =
Token IDENTIFIER: temp
Token SEMICOLON: ;
Token KEYWORD_ENDDEF: enddef
Token SEMICOLON: ;
Token KEYWORD_DEF: def
Token IDENTIFIER: quickSort
Token L_PARENTHESIS: (
Token IDENTIFIER: a
Token L_BRACKET: [
Token R_BRACKET: ]
Token COLON: :
Token KEYWORD_INTEGER: integer
Token COMMA: ,
Token IDENTIFIER: low
Token COLON: :
Token KEYWORD_INTEGER: integer
Token COMMA: ,
Token IDENTIFIER: high
Token COLON: :
Token KEYWORD_INTEGER: integer
Token R_PARENTHESIS: )
Token OP_MINUS: -
Token OP_GREATER: >
Token IDENTIFIER: void
